name: Manually Purge CDN Caches

on:
  workflow_dispatch:

jobs:
  purge-caches:
    runs-on: ubuntu-latest
    steps:
      # 第一步：刷新 Cloudflare 缓存，这部分没有问题
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'

      # 第二步：配置腾讯云凭证，使用正确的官方 Action
      - name: Configure Tencent Cloud Credentials
        # --- 这是修正后的关键部分 ---
        uses: TencentCloud/tencentcloud-sdk-auth-action@v1 # 使用官方正确的 Action 名称
        # --------------------------
        with:
          secret-id: ${{ secrets.TENCENT_SECRET_ID }}
          secret-key: ${{ secrets.TENCENT_SECRET_KEY }}
          region: ap-guangzhou 
      
      # 第三步：安装并执行 EdgeOne 的 CLI，这部分依赖于上一步的凭证配置
      - name: Install Tencent Cloud CLI for EdgeOne
        run: |
          pip install tccli-edgeone
          
      - name: Run Purge EdgeOne Cache Command
        run: |
          tccli edgeone PurgeCache --ZoneId ${{ secrets.EDGEONE_ZONE_ID }} --Type purge_all