name: Manually Purge CDN Caches

on:
  workflow_dispatch:

jobs:
  purge-caches:
    runs-on: ubuntu-latest
    steps:
      # 第一步：刷新 Cloudflare 缓存
      # 通过 CLOUDFLARE_ZONE_ID 指定要刷新的站点
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'

      # 第二步：安装统一的腾讯云CLI
      - name: Install Tencent Cloud CLI
        run: pip install tccli
      
      # 第三步：执行EdgeOne缓存刷新命令
      # 通过 EDGEONE_ZONE_ID 指定要刷新的站点
      - name: Run Purge EdgeOne Cache Command
        env:
          TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          TENCENTCLOUD_REGION: "ap-guangzhou"
        run: |
          tccli teo CreatePurgeTask --ZoneId ${{ secrets.EDGEONE_ZONE_ID }} --Type purge_all